# Generated by Django 5.2.14 on 2026-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nom du responsable du département', max_length=100),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('PRESTATAIRE', 'Prestataire')], max_length=20),
        ),
    ]
